### ISSUE TITLE
Panic invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by elghazal-a** [foomo/pagespeed_exporter#60]
Hello, the exporter has been working for years until yesterday when it started throwing this error

```
time="2024-05-10T08:21:11Z" level=info msg="starting pagespeed exporter version 1a13ba6 on address :9271 for 4 targets"
time="2024-05-10T08:24:36Z" level=info msg="starting pagespeed exporter version 1a13ba6 on address :9271 for 4 targets"
time="2024-05-10T08:29:50Z" level=info msg="starting pagespeed exporter version 1a13ba6 on address :9271 for 4 targets"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x9844e1]

goroutine 112 [running]:
github.com/foomo/pagespeed_exporter/collector.collectLighthouseResults({0xaeee7a, 0xa}, 0xc0002621e0, 0x405d3d?, 0xc0000b03c0?)
  /app/collector/collector.go:181 +0x3e1
github.com/foomo/pagespeed_exporter/collector.collect(0xc0002480c0, 0x2?)
  /app/collector/collector.go:127 +0xbe
github.com/foomo/pagespeed_exporter/collector.collector.Collect({{0xc00025c500, 0x8, 0x8}, {0xbd1020, 0xc00021a9e0}, 0x1}, 0x4?)
  /app/collector/collector.go:101 +0x391
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
  /go/pkg/mod/github.com/prometheus/client_golang@v1.5.1/prometheus/registry.go:443 +0x10d
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
  /go/pkg/mod/github.com/prometheus/client_golang@v1.5.1/prometheus/registry.go:535 +0xb89
time="2024-05-10T08:34:52Z" level=info msg="starting pagespeed exporter version 1a13ba6 on address :9271 for 4 targets"
```

**Comment by smartinov** [comment]
I'll get on it!

**Comment by jmtsi** [comment]
Thank you @smartinov for a fast fix!
